const test = require('node:test');
const assert = require('node:assert/strict');

const { GameService } = require('../src/services/gameService');

// Create an isolated GameService for tests that do not examine persistence directly.
// The fake repository prevents unit tests from connecting to Prisma.
function createTestService() {
  let nextGameId = 1;

  return new GameService({
    gameRepository: {
      // Simulate Prisma creating a Game record with a numeric database ID.
      async createGame(players) {
        return {
          id: nextGameId++,
          ...players,
        };
      },
    },
  });
}

test('creates a game in the initial position', async () => {
  const service = createTestService();

  // Wait until the fake repository returns the database record.
  const game = await service.createGame({
    whiteId: 1,
    blackId: 2,
  });

  assert.equal(game.whiteId, 1);
  assert.equal(game.blackId, 2);
  assert.equal(game.turn, 'w');
  assert.equal(game.status, 'IN_PROGRESS');
  assert.equal(game.result, null);
  assert.equal(game.winnerId, null);
  assert.equal(
    game.fen,
    'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  );
});

test('persists a new game and uses the database id as gameId', async () => {
  // Store the arguments received by the fake repository.
  // This lets us verify that GameService passes the correct players to the persistence layer.
  let persistedPlayers = null;

  // Replace the real Prisma repository with a small fake implementation.
  // Unit tests should not depend on a running database.
  const fakeGameRepository = {
    // Imitate the asynchronous createGame method of the real repository.
    async createGame(players) {
      // Remember the received player IDs so they can be checked below.
      persistedPlayers = players;

      // Imitate the object that Prisma returns after creating a Game record.
      // The database generates id 42, while the player IDscome from the input.
      return {
        id: 42,
        ...players,
      };
    },
  };

  // Inject the fake repository instead of using the real Prisma repository.
  // This isolates GameService and gives the test full control over database results.
  const service = new GameService({
    gameRepository: fakeGameRepository,
  });

  // Ask the service to create a game between users 1 and 2.
  // The method must wait for the repository before returning the game state.
  const game = await service.createGame({
    whiteId: 1,
    blackId: 2,
  });

  // Verify that GameService passes both player IDs to the repository unchanged.
  // If the repository is never called, persistedPlayers remains null.
  assert.deepEqual(persistedPlayers, {
    whiteId: 1,
    blackId: 2,
  });

  // Verify thet the in-memory game uses the ID generated by the database.
  // This ID will later identify the same game in Prisma, Socket.io and the frontend.
  assert.equal(game.gameId, 42);
});

test('accepts a legal move and rejects invalid moves', async () => {
  const service = createTestService();
  const game = await service.createGame({
    whiteId: 1,
    blackId: 2,
  });

  const afterLegalMove = service.makeMove({
    gameId: game.gameId,
    playerId: 1,
    from: 'e2',
    to: 'e4',
  });

  assert.equal(afterLegalMove.turn, 'b');

  assert.throws(
    () =>
      service.makeMove({
        gameId: game.gameId,
        playerId: 1,
        from: 'g1',
        to: 'f3',
      }),
    /turn/,
  );

  assert.throws(
    () =>
      service.makeMove({
        gameId: game.gameId,
        playerId: 2,
        from: 'e7',
        to: 'e4',
      }),
    /Illegal move/,
  );

  assert.equal(
    service.getGame(game.gameId).fen,
    afterLegalMove.fen,
  );
});

test('finishes the game after checkmate', async () => {
  const service = createTestService();
  const game = await service.createGame({
    whiteId: 1,
    blackId: 2,
  });

  service.makeMove({
    gameId: game.gameId,
    playerId: 1,
    from: 'f2',
    to: 'f3',
  });

  service.makeMove({
    gameId: game.gameId,
    playerId: 2,
    from: 'e7',
    to: 'e5',
  });

  service.makeMove({
    gameId: game.gameId,
    playerId: 1,
    from: 'g2',
    to: 'g4',
  });

  const finished = service.makeMove({
    gameId: game.gameId,
    playerId: 2,
    from: 'd8',
    to: 'h4',
  });

  assert.equal(finished.status, 'COMPLETED');
  assert.equal(finished.result, 'BLACK_WIN');
  assert.equal(finished.winnerId, 2);
  assert.match(finished.pgn, /\[Result "0-1"\]/);

  assert.throws(
    () =>
      service.makeMove({
        gameId: game.gameId,
        playerId: 1,
        from: 'a2',
        to: 'a3',
      }),
    /completed/,
  );
});

test('finishes the game after threefold repetition', async () => {
  const service = createTestService();
  const game = await service.createGame({
    whiteId: 1,
    blackId: 2,
  });

  const moves = [
    [1, 'g1', 'f3'],
    [2, 'g8', 'f6'],
    [1, 'f3', 'g1'],
    [2, 'f6', 'g8'],
    [1, 'g1', 'f3'],
    [2, 'g8', 'f6'],
    [1, 'f3', 'g1'],
    [2, 'f6', 'g8'],
  ];

  let finished;

  for (const [playerId, from, to] of moves) {
    finished = service.makeMove({
      gameId: game.gameId,
      playerId,
      from,
      to,
    });
  }

  assert.equal(finished.status, 'COMPLETED');
  assert.equal(finished.result, 'DRAW');
  assert.equal(finished.winnerId, null);
  assert.match(finished.pgn, /\[Result "1\/2-1\/2"\]/);
});

test('allows a player to resign outside their turn', async () => {
  const service = createTestService();
  const game = await service.createGame({
    whiteId: 1,
    blackId: 2,
  });

  const finished = service.resignGame({
    gameId: game.gameId,
    playerId: 2,
  });

  assert.equal(finished.status, 'COMPLETED');
  assert.equal(finished.result, 'WHITE_WIN');
  assert.equal(finished.winnerId, 1);
  assert.match(finished.pgn, /\[Result "1-0"\]/);
});
